"""Forbid storing any response from this API.

WHY BLANKET, AND WHY no-store SPECIFICALLY.

Before this, no response in the application carried a Cache-Control header of
any kind — including GET /api/exports/payments, which returns every invoice
with its client's name in a plain cacheable GET.

The exposure that matters is not that browsers eagerly cache XHR JSON; mostly
they do not. It is that a response with no cache directives MAY be written to
the browser's on-disk HTTP cache, and what is on disk outlives the session.
After logout, or after the 30-minute token expires, those client records are
still on the workstation and readable with no session at all. On a shared
clinic machine that is PHI at rest, outside anything this application
controls. `no-store` is the only directive that forbids writing the response
to storage in the first place — no-cache, must-revalidate and a zero max-age
all still permit STORING it and merely require revalidation before REUSE.

The rest is defence in depth rather than the main event:

  * `private`             — bars shared/intermediary caches from storing it.
  * `no-cache`,
    `must-revalidate`     — force revalidation in anything that stored it
                            anyway, e.g. an intermediary that ignores no-store.
  * `Pragma`, `Expires`   — HTTP/1.0 relics. Ignored by everything modern, but
                            free, and old proxies do still exist.

Applied to EVERY response rather than to a list of PHI-returning routes. Such
a list is something a human has to maintain, and the failure mode of
forgetting an entry is silent — which is precisely how this finding came to
exist. This service returns no static assets (the frontend is a separate
deployment) and the client caches in memory via React Query rather than
relying on HTTP caching, so a blanket policy costs nothing. If an endpoint
ever genuinely needs to be cacheable, that should be an explicit change to
this file, which is the right amount of friction for an API that serves PHI.
"""
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

CACHE_CONTROL = "no-store, no-cache, must-revalidate, private"


class NoStoreCacheMiddleware(BaseHTTPMiddleware):
    """Stamp no-store on everything.

    Register this LAST in main.py so it ends up outermost (Starlette runs the
    most recently added middleware first) and therefore also covers responses
    generated by other middleware — a CSRF rejection carrying a PHI-adjacent
    error detail should be no more storable than the data itself.

    Set unconditionally, overwriting any existing value. Nothing in this API
    sets one today, and an endpoint that wants different behaviour should have
    to come here and say so.
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
        response.headers["Cache-Control"] = CACHE_CONTROL
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        return response
