"""add converted_client_id to leads

Revision ID: 3a67ae487d98
Revises: aa56ddb31609
Create Date: 2026-07-10 20:46:03.716208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a67ae487d98'
down_revision: Union[str, None] = 'aa56ddb31609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('converted_client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leads', 'clients', ['converted_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'converted_client_id')
    # ### end Alembic commands ###
