"""add note to leads and clients

The admin's own short note about a person, surfaced by hovering their name in
the leads and clients tables. Copied from the lead onto the client when the
lead is converted, which is why both tables carry the identical column.

Distinct from the columns that already look adjacent:
  - leads.message      what the CLIENT wrote on the website form, never edited
  - follow_ups.notes   attached to a due date, part of a task
  - client_messages    logged communications

100 characters because it is read in a hover card.

HAND-WRITTEN, not autogenerated. Autogenerate proposed dropping eighteen
indexes and the `integrations` table alongside these two columns: the
functional and partial indexes (lower(email), external_ref WHERE NOT NULL,
uq_active_enrollment, ...) were created with raw SQL in earlier revisions and
are invisible to its model comparison, so it reads them as drift. Only the two
ADD COLUMNs below are intended.

Revision ID: 4e7df0fd1759
Revises: c2f9a5b31e88
Create Date: 2026-09-01 16:34:03.105825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4e7df0fd1759'
down_revision: Union[str, None] = 'c2f9a5b31e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOTE_LENGTH = 100


def upgrade() -> None:
    op.add_column('leads', sa.Column('note', sa.String(length=NOTE_LENGTH), nullable=True))
    op.add_column('clients', sa.Column('note', sa.String(length=NOTE_LENGTH), nullable=True))


def downgrade() -> None:
    op.drop_column('clients', 'note')
    op.drop_column('leads', 'note')
