"""make role_requests.requested_role_id nullable

Revision ID: 56de65205381
Revises: bb394f29a32d
Create Date: 2026-07-15 01:10:54.319016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56de65205381'
down_revision: Union[str, None] = 'bb394f29a32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_requests', 'requested_role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_requests', 'requested_role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
