"""add revoked_tokens table

Revision ID: 6051f9682593
Revises: bc8787b93f75
Create Date: 2026-08-03 21:46:46.246405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6051f9682593'
down_revision: Union[str, None] = 'bc8787b93f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # NOTE: autogenerate also proposed `op.drop_table('integrations')` here,
    # since the Integration model was removed from the codebase separately.
    # Deliberately left out — dropping a table is destructive and wasn't
    # asked for in this change; do it as its own explicit, confirmed step.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
