"""add unique constraint on therapists email

Revision ID: b782739a615b
Revises: 16ff39e433e0
Create Date: 2026-07-20 20:03:46.679642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b782739a615b'
down_revision: Union[str, None] = '16ff39e433e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('therapists_email_key', 'therapists', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('therapists_email_key', 'therapists', type_='unique')
    # ### end Alembic commands ###
