"""add date and reason to pto_transactions

Revision ID: f063485678f1
Revises: 90f8eeec000b
Create Date: 2026-07-21 02:54:42.636027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f063485678f1'
down_revision: Union[str, None] = '90f8eeec000b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pto_transactions', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('pto_transactions', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pto_transactions', 'reason')
    op.drop_column('pto_transactions', 'date')
    # ### end Alembic commands ###
